<?php

use vova07\imperavi\Widget;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
* @var yii\web\View $this
* @var common\models\Offer $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="offer-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'enableClientValidation' => false]); ?>

    <div class="">
        <?php echo $form->errorSummary($model); ?>
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'action_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\OfferAction::find()->all(),'id','title'),
    ['prompt'=>'Choose...']
); ?>
			<?= $form->field($model, 'price')->textInput() ?>
            <?= $form->field($model, 'our_percent')->textInput();?>
            <?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'region_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Region::find()->all(),'id','title'),
    ['prompt'=>'Choose...']
); ?>
			<?= $form->field($model, 'lead')->textInput(['maxlength' => 255]) ?>
			<?= $form->field($model, 'hold')->textInput() ?>
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'access_type_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\AccessType::find()->all(),'id','title'),
    ['prompt'=>'Choose...']
); ?>
			<?= $form->field($model, 'cpe')->textInput(['maxlength' => 255]) ?>
			<?= $form->field($model, 'postclick')->textInput() ?>
            <?= $form->field($model,'site')->widget(\yii\widgets\MaskedInput::className(),[
                'name' => 'site',
                'clientOptions' => [
                    'alias' =>  'url',
                ],])?>
            <?= $form->field($model, 'caption')->widget(Widget::className(), [
                'settings' => [
                    'lang' => 'ru',
                    'minHeight' => 200,
                    'plugins' => [
                        'clips',
                        'fullscreen'
                    ]
                ]
            ]);?>
            <?= $form->field($model, 'traff_1')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_2')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_3')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_4')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_5')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_6')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_7')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_8')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_9')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_10')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'traff_11')->radioList([ 'Y' => 'Разрешен', 'N' => 'Запрещен' ]) ?>
            <?= $form->field($model, 'create_time')->widget(\kartik\datetime\DateTimePicker::classname(), [
                //'name' => 'create_time',
                'language'=>'ru',
                'options' => ['placeholder' => 'Select operating time ...'],
                //'convertFormat' => true,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd hh:ii',
                    'todayHighlight' => true
                ]
            ]) ?>
			<?= $form->field($model, 'status')->radioList([ 'active' => 'Active', 'pause' => 'Pause', ]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    \yii\bootstrap\Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Offer',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?= Html::submitButton('<span class="glyphicon glyphicon-check"></span> '.($model->isNewRecord ? 'Create' : 'Save'), ['class' => $model->isNewRecord ?
        'btn btn-primary' : 'btn btn-primary']) ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
