<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
* @var yii\web\View $this
* @var common\models\Statistic $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="statistic-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'enableClientValidation' => false]); ?>

    <div class="">
        <?php echo $form->errorSummary($model); ?>
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'offer_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Offer::find()->all(),'id','title'),
    ['prompt'=>'Choose...']
); ?>
			<?= // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
$form->field($model, 'user_ref_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\User::find()->all(),'id','name'),
    ['prompt'=>'Choose...']
); ?>
			<?= $form->field($model, 'hits')->textInput() ?>
			<?= $form->field($model, 'visitors')->textInput() ?>
			<?= $form->field($model, 'tb')->textInput() ?>
			<?= $form->field($model, 'leads')->textInput() ?>
			<?= $form->field($model, 'confirmed')->textInput() ?>
			<?= $form->field($model, 'question')->textInput() ?>
			<?= $form->field($model, 'warning')->textInput() ?>
			<?= $form->field($model, 'hold')->textInput() ?>
			<?= $form->field($model, 'profit')->textInput() ?>
			<?= $form->field($model, 'date')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    \yii\bootstrap\Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Statistic',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?= Html::submitButton('<span class="glyphicon glyphicon-check"></span> '.($model->isNewRecord ? 'Create' : 'Save'), ['class' => $model->isNewRecord ?
        'btn btn-primary' : 'btn btn-primary']) ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
